#!/bin/bash

# Runs the dockerfile
sudo docker run -it dohtest /bin/bash

#--------------------------------------------------------------------------------------------------
# This section copies the CSV file generated by Dohlyzer from the Docker container to the host
# machine within the "CSV_files" folder after the user exits the container.
#--------------------------------------------------------------------------------------------------
container_id=$(sudo docker ps -l --format "{{.ID}}")
cd CSV_files
sudo docker start $container_id
sudo docker cp $container_id:/code/capture/capturedPackets.csv .
sudo docker stop $container_id

